/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dashboard;

import SessionID.SessionSection;
import Login.Database;
import Login.Login;
import SessionID.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Resource.HoverAnimation;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author User
 */
public class Section extends javax.swing.JFrame {

    String id;
    String first;
    String middle;
    String last;
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    public Section() {
        initComponents();
        conn = Database.conn();
        table(); // table
        ImageIcon logo = new ImageIcon(getClass().getResource("/Resource/aclclogo.png"));//Image
        jimage.setIcon(logo);
        ImageIcon icon = new ImageIcon(getClass().getResource("/Resource/aclcicon.png"));
        setIconImage(icon.getImage());

    }

    public Section(String TeacherID, String firstname, String middlename, String lastname) {
        this();
        this.id = TeacherID;
        this.first = firstname;
        this.middle = middlename;
        this.last = lastname;
        jid.setText(TeacherID);
        jname.setText(first + " " + middle + " " + last + "!");

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int confirm = JOptionPane.showConfirmDialog(
                        null,
                        "Are you sure you want to log out and close this window?",
                        "Confirm Logout",
                        JOptionPane.YES_NO_OPTION
                );

                if (confirm == JOptionPane.YES_OPTION) {
                    new Login().setVisible(true);
                    dispose();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jimage = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jid = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Section");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jimage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(jimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 130));

        jTable1.setBackground(new java.awt.Color(242, 242, 242));
        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 90, 172));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Sections"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 167, 730, 480));

        jid.setFont(new java.awt.Font("Segoe UI", 0, 1)); // NOI18N
        jid.setText("jLabel1");
        getContentPane().add(jid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 60, 40));

        jPanel2.setBackground(new java.awt.Color(0, 90, 172));

        jname.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jname.setText("placeholder(name)");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setText("Welcome");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jname, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jname, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 170));

        jPanel3.setBackground(new java.awt.Color(0, 71, 171));

        jback.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jback.setText("Back");
        jback.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(751, Short.MAX_VALUE)
                .addComponent(jback, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(389, Short.MAX_VALUE)
                .addComponent(jback, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 880, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2 && jTable1.getSelectedRow() != -1) { //clicking Jtable row function
            int selectedRow = jTable1.getSelectedRow();
            String sectionname = (String) jTable1.getValueAt(selectedRow, 0);
            int teacherid = SessionTeacher.loggedInTeacherId;

            try {
                String sql = "SELECT * FROM `section` WHERE `SectionName`=? AND `TeacherID`=?";

                pst = conn.prepareStatement(sql);
                pst.setString(1, sectionname);
                pst.setInt(2, teacherid);
                rs = pst.executeQuery();

                while (rs.next()) {
                    String sectionid = rs.getString("SectionID");
                    String id = jid.getText();
                    String firstname = first;
                    String middlename = middle;
                    String lastname = last;
                    int SectionID = getSectionID(Integer.parseInt(sectionid));
                    SessionSection.AccessID = SectionID;
                    new Subject(sectionname, id, firstname, middlename, lastname).setVisible(true);
                    this.setVisible(false);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbackActionPerformed
        new SemesterSelection(this.id, this.first, this.middle, this.last).setVisible(true); // Logout function
        this.setVisible(false);
    }//GEN-LAST:event_jbackActionPerformed

    public int getSectionID(int SectionID) { // get SectionID for SessionSection in SessionID. (SectionID) becomes static
        String sql = "SELECT * FROM `section` WHERE `SectionID` = ?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setInt(1, SectionID);
            rs = pst.executeQuery();

            if (rs.next()) {
                SectionID = rs.getInt("SectionID");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error retrieving SubjectID: " + e.getMessage());
        }

        return SectionID;
    }

    private void table() {
        int teacherId = SessionTeacher.loggedInTeacherId; // from session
        int semesterId = SessionSemester.SemesterID; // make sure semesterID is stored and passed correctly

        try {
            String sql = "SELECT * FROM `section` WHERE `TeacherID` = ? AND `SemesterID` = ?";
            pst = conn.prepareStatement(sql);
            pst.setInt(1, teacherId);
            pst.setInt(2, semesterId);

            rs = pst.executeQuery();

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // clear table

            while (rs.next()) {
                model.addRow(new String[]{
                    rs.getString("SectionName")
                    
                });
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Error loading table: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Section().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jback;
    private javax.swing.JLabel jid;
    private javax.swing.JLabel jimage;
    private javax.swing.JLabel jname;
    // End of variables declaration//GEN-END:variables
}
