/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DashboardAdmin;

import Login.Database;
import Resource.HoverAnimation;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import SessionID.*;
import Validation.SectionValidation;
import java.awt.HeadlessException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.util.Random;

/**
 *
 * @author User
 */
public class SectionRegistration extends javax.swing.JFrame implements SectionValidation { // implements from Validation in SectionValidation interface

    String id;
    String first;
    String middle;
    String last;
    Connection conn = null;
    Statement st = null;

    public SectionRegistration() {
        initComponents();
        HoverAnimation.HoverAnimationSection(jaddsection); //HoverAnimation in Resource packagfe
        conn = Database.conn();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Resource/aclcicon.png"));
        setIconImage(icon.getImage());
    }

    SectionRegistration(String id, String firstname, String middlename, String lastname) {
        this();
        this.id = id;
        this.first = firstname;
        this.middle = middlename;
        this.last = lastname;

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                new SectionAdmin(id, firstname, middlename, lastname).setVisible(true);
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBack = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jsection = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jaddsection = new javax.swing.JButton();
        errorsection = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Section Registration");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBack.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jBack.setText("<---");
        jBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBackMouseClicked(evt);
            }
        });
        getContentPane().add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Section Register");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, 30));

        jsection.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jsection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsectionActionPerformed(evt);
            }
        });
        getContentPane().add(jsection, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 310, 40));

        jPanel1.setBackground(new java.awt.Color(0, 90, 172));

        jaddsection.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jaddsection.setText("Add Section");
        jaddsection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddsectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jaddsection, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(errorsection, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(errorsection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jaddsection, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 280));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackMouseClicked
        new SectionAdmin(this.id, this.first, this.middle, this.last).setVisible(true);
        this.setVisible(false);//Going back to Section form
    }//GEN-LAST:event_jBackMouseClicked

    private void jsectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsectionActionPerformed

    private void jaddsectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddsectionActionPerformed
        String section = jsection.getText(); // Adding new Section
        boolean isValid = emptySection(section, errorsection); // Check if it's empty

        if (!isValid) {
            return; // Return if empty
        }

        try {
            st = conn.createStatement();

            st.executeUpdate("INSERT INTO `section`(`SemesterID`,`SectionName`, `TeacherID`)"
                    + "VALUES ('" + SessionSemester.SemesterID + "','" + section + "','" + SessionTeacher.loggedInTeacherId + "')");

            JOptionPane.showMessageDialog(rootPane, "Section Created!");

            this.setVisible(false);
            new SectionAdmin(this.id, this.first, this.middle, this.last).setVisible(true);

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jaddsectionActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SectionRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SectionRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SectionRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SectionRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SectionRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorsection;
    private javax.swing.JLabel jBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jaddsection;
    private javax.swing.JTextField jsection;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean emptySection(String section, JLabel errorsection) { // implements method from SectionValidation
        boolean isValid = true;
        if (section.isEmpty()) {
            setError(errorsection, "Section name cannot be empty.");
            isValid = false;
        } else {
            clearError(errorsection);
        }
        return isValid;
    }

    @Override
    public void setError(JLabel label, String message) {
        label.setText(message);
        label.setForeground(java.awt.Color.RED);
    }

    @Override
    public void clearError(JLabel label) {
        label.setText("");
    }
}
