/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DashboardAdmin;

import SessionID.*;
import Login.Database;
import Resource.HoverAnimation;
import Validation.SubjectValidation;
import java.awt.HeadlessException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class SubjectRegistration extends javax.swing.JFrame implements SubjectValidation { // implements from SubjectValidation in Validation package

    String id;
    String first;
    String middle;
    String last;
    String section;
    Connection conn = null;
    Statement st = null;

    public SubjectRegistration() {
        initComponents();
        conn = Database.conn();
        HoverAnimation.HoverAnimationSection(jaddsubject); // HoverAnimation class in Resource
        ImageIcon icon = new ImageIcon(getClass().getResource("/Resource/aclcicon.png"));
        setIconImage(icon.getImage());
    }

    SubjectRegistration(String section, String id, String firstname, String middlename, String lastname) {
        this();
        this.section = section;
        this.id = id;
        this.first = firstname;
        this.middle = middlename;
        this.last = lastname;

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                new SubjectAdmin(section, id, firstname, middlename, lastname).setVisible(true);
                dispose();
            }
        });
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jsubject = new javax.swing.JTextField();
        jaddsubject = new javax.swing.JButton();
        jback = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        errorsubject = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Subject Registration");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Subject Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jsubject.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jsubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 300, 50));

        jaddsubject.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jaddsubject.setText("Add Subject");
        jaddsubject.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jaddsubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddsubjectActionPerformed(evt);
            }
        });
        getContentPane().add(jaddsubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 160, 60));

        jback.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jback.setText("<--");
        jback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbackMouseClicked(evt);
            }
        });
        getContentPane().add(jback, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 90, 172));

        errorsubject.setPreferredSize(new java.awt.Dimension(37, 16));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(errorsubject, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(errorsubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jaddsubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddsubjectActionPerformed
        String subject = jsubject.getText(); // Adding subject
    String randomCode = generateRandomCode(); // Generate a random E-Code
    String randomCode2 = generateRandomCode();
    boolean isValid = emptySubject(subject, errorsubject); // Check if empty

    if (!isValid) {
        return; // Return if empty
    }

    try {
        st = conn.createStatement();

        st.executeUpdate("INSERT INTO `subject`(`SubjectName`,`E-Code`,`SubjectCode`, `SectionID` )"
                + "VALUES ('" + subject + "','" + randomCode + "','"+randomCode2 +"','" + SessionSection.AccessID + "')");

        JOptionPane.showMessageDialog(rootPane, "Subject Created!");

        this.setVisible(false);
        new SubjectAdmin(this.section, this.id, this.first, this.middle, this.last).setVisible(true);

    } catch (HeadlessException | SQLException e) {
        JOptionPane.showMessageDialog(rootPane, "Error creating subject: " + e.getMessage());
    }
    }//GEN-LAST:event_jaddsubjectActionPerformed

    private void jbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbackMouseClicked
        new SubjectAdmin(this.section, this.id, this.first, this.middle, this.last).setVisible(true); //going back to Subject form
        this.setVisible(false);
    }//GEN-LAST:event_jbackMouseClicked

    private String generateRandomCode() {
        String letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String numbers = "0123456789";
        StringBuilder result = new StringBuilder();
        Random random = new Random();

        // Generate 3 random letters
        for (int i = 0; i < 3; i++) {
            result.append(letters.charAt(random.nextInt(letters.length())));
        }

        // Generate 3 random numbers
        for (int i = 0; i < 3; i++) {
            result.append(numbers.charAt(random.nextInt(numbers.length())));
        }

        return result.toString();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorsubject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jaddsubject;
    private javax.swing.JLabel jback;
    private javax.swing.JTextField jsubject;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean emptySubject(String Subject, JLabel errorsubject) { // implement method from SubjectValidation interface
        boolean isValid = true;
        if (Subject.isEmpty()) {
            setError(errorsubject, "Subject name cannot be empty.");
            isValid = false;
        } else {
            clearError(errorsubject);
        }
        return isValid;
    }

    @Override
    public void setError(JLabel label, String message) {
        label.setText(message);
        label.setForeground(java.awt.Color.RED);
    }

    @Override
    public void clearError(JLabel label) {
        label.setText("");
    }
}
